#!/usr/bin/python
class atom(object):
	def __init__(self,atno,x,y,z):
		self.atno = atno
		self.position = (x,y,z)
	def symbol(self): # a class method
		return Atno_to_Symbol[atno]
	def __repr__(self): #overloads printing
		return '%d %10.4f %10.4f %10.4f' % 
		(self.atno, self.position[0],self.position[1],self.position[2])
		
print  at = atom(6,0.0,1.0,2.0)